# Hugo configuration for hugo-paper theme
# https://github.com/nanxiaobei/hugo-paper

baseURL = "https://soft-choux-a40e6f.netlify.app/"
languageCode = "zh-CN"
title = "Linki"
theme = "paper"

[params]
  dateFormat = "2006-01-02"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Contact"
    url = "mailto:linkiouob@163.com"
    weight = 2
  [[menu.main]]
    name = "Editor"
    url = "/admin/"
    weight = 3
