backend:
  name: git-gateway
  branch: main
  # Replace with your GitHub username and repo name:
  # repo: your-username/your-repo-name

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Posts"
    label_singular: "Post"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary: "{{title}} — {{date}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Date"
        name: "date"
        widget: "datetime"
        default: "{{now}}"
        date_format: "YYYY-MM-DD"
        time_format: false
      - label: "Body"
        name: "body"
        widget: "markdown"
